### ISSUE TITLE
Cross Domain

### ISSUE THREAD

**Issue by ilitotor** [HackAfro/django-push#1]
I´m trying to implement web push with Django. But when I tried to reference registerSW.js in another host, as a localhost, for example, I get:
_" has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'._

For example, my index.html hosted in another domain has:
```
<head>
   <script src="sw.js"></script>
    <script src="http://ilito.pythonanywhere.com/static/js/registerSw.js"></script>
</head>
```

I wanna just put this js´s in other domains and send the push message from the other domain.

**Comment by HackAfro** [comment]
To achieve this, I think you have to provision headers to allow requests from different origins. You have to provision headers to allow external requests to the `http://ilito.pythonanywhere.com/` domain.

Check out this article: https://www.techiediaries.com/django-cors/

**Comment by ilitotor** [comment]
> To achieve this, I think you have to provision headers to allow requests from different origins. You have to provision headers to allow external requests to the `http://ilito.pythonanywhere.com/` domain.
> 
> Check out this article: https://www.techiediaries.com/django-cors/

Thanks! This problem is gone, but.....

Now I get "you can´t send push notifications". It´s look like the "if ('serviceWorker' in navigator) " is False.
But I´m using chrome and firefox.
Ex: http://esportefavorito.com/push/teste.html

**Comment by HackAfro** [comment]
It's not the fault of the browser. Your domain isn't secure and Service workers only work on secure domains (`SSL` enabled). Currently, it doesn't like your site is served from an `https` domain.
